/* automatically generated by rust-bindgen 0.71.1 */

pub type adiós = ::std::os::raw::c_int;
pub type 数字 = ::std::os::raw::c_int;
unsafe extern "C" {
    pub fn ϒ();
}
unsafe extern "C" {
    pub fn 拜拜();
}
unsafe extern "C" {
    pub fn Say拜拜();
}
