/* automatically generated by rust-bindgen 0.70.1 */

pub type adiós = ::std::os::raw::c_int;
pub type 数字 = ::std::os::raw::c_int;
extern "C" {
    pub fn ϒ();
}
extern "C" {
    pub fn 拜拜();
}
extern "C" {
    pub fn Say拜拜();
}
