/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    #[link_name = "\u{1}my_variable_label"]
    pub static mut asm_labeled_variable: ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[link_name = "\u{1}my_function_label"]
    pub fn asm_labeled_function(
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
