/* automatically generated by rust-bindgen 0.71.1 */

pub type sym = ::std::os::raw::c_char;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pt {
    pub x: f64,
    pub y: f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pt"][::std::mem::size_of::<pt>() - 16usize];
    ["Alignment of pt"][::std::mem::align_of::<pt>() - 8usize];
    ["Offset of field: pt::x"][::std::mem::offset_of!(pt, x) - 0usize];
    ["Offset of field: pt::y"][::std::mem::offset_of!(pt, y) - 8usize];
};
