/* automatically generated by rust-bindgen 0.70.1 */

pub type an_pchar = *const ::std::os::raw::c_char;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MyCoolStruct {
    pub listOfNames: [[::std::os::raw::c_char; 255usize]; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of MyCoolStruct"][::std::mem::size_of::<MyCoolStruct>() - 2040usize];
    ["Alignment of MyCoolStruct"][::std::mem::align_of::<MyCoolStruct>() - 1usize];
    [
        "Offset of field: MyCoolStruct::listOfNames",
    ][::std::mem::offset_of!(MyCoolStruct, listOfNames) - 0usize];
};
pub type foo = ::std::option::Option<
    unsafe extern "C" fn(arg1: ::std::os::raw::c_int) -> ::std::os::raw::c_int,
>;
extern "C" {
    pub static mut my_array: [::std::option::Option<
        unsafe extern "C" fn(arg1: ::std::os::raw::c_int) -> ::std::os::raw::c_int,
    >; 1usize];
}
