#!/usr/bin/env bash

set -e

usage() {
    echo "Usage: $(basename "$0") [FILE]"
    echo
    echo "If no FILE is provided, compile '*.pp.hs' files."
    echo "Skip expected failures."

}

failures=(
    # GCC compilation errors (error happens when parsing inlined C source).
    "adios.pp.hs"           # NFC.
    "manual_examples.pp.hs" # NFC.
    "weird01.pp.hs"         # "Declaration does not declare anything" error.
    # GHC compilation errors.
    "macro_functions.pp.hs"  # Import error ("type" keyword required).
    "macro_in_fundecl.pp.hs" # "Illegal type" error.
    "macro_strings.pp.hs"    # "A section must be enclosed in parentheses" error
    "macro_types.pp.hs"      # "Illegal type" error.
    "typedef_vs_macro.pp.hs" # "Illegal type" error.
    "typenames.pp.hs"        # "Multiple declarations" error.
    "type_naturals.pp.hs"    # "Illegal type" error.
    "vector.pp.hs"           # "unknown type name ‘import’" (wrong import from 'vector-algorithms/vector.h')?
)

compile_one() {
    file="$1"
    echo "Compiling $file"
    cabal exec -- \
        ghc -fforce-recomp \
        -optc -I"../examples" \
        "$file"
}

compile_all() {
    for f in *.pp.hs; do
        if [[ " ${failures[*]} " =~ [[:space:]]${f}[[:space:]] ]]; then
            echo "Skipping test $f; expected failure"
        else
            compile_one "$f"
        fi
    done
}

# Ensure the build is up-to-date.
cabal build all

if [ $# -lt 1 ]; then
    compile_all
elif [ $# -eq 1 ]; then
    compile_one "$1"
else
    usage
fi
