/* automatically generated by rust-bindgen 0.70.1 */

pub const first_FIRST1: first = 0;
pub const first_FIRST2: first = 1;
pub type first = ::std::os::raw::c_uint;
pub const second_SECOND_A: second = -1;
pub const second_SECOND_B: second = 0;
pub const second_SECOND_C: second = 1;
pub type second = ::std::os::raw::c_int;
pub const same_SAME_A: same = 1;
pub const same_SAME_B: same = 1;
pub type same = ::std::os::raw::c_uint;
pub const packad_PACKED_A: packad = 0;
pub const packad_PACKED_B: packad = 1;
pub const packad_PACKED_C: packad = 2;
pub type packad = ::std::os::raw::c_uchar;
