/* automatically generated by rust-bindgen 0.70.1 */

extern "C" {
    pub fn fun_1(
        x: ::std::os::raw::c_int,
        xs: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
pub type triple = [::std::os::raw::c_int; 3usize];
extern "C" {
    pub fn fun_2(xs: *mut ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
