/* automatically generated by rust-bindgen 0.70.1 */

pub type triple = [::std::os::raw::c_int; 3usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Example {
    pub triple: [::std::os::raw::c_int; 3usize],
    pub sudoku: [[::std::os::raw::c_int; 3usize]; 3usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Example"][::std::mem::size_of::<Example>() - 48usize];
    ["Alignment of Example"][::std::mem::align_of::<Example>() - 4usize];
    [
        "Offset of field: Example::triple",
    ][::std::mem::offset_of!(Example, triple) - 0usize];
    [
        "Offset of field: Example::sudoku",
    ][::std::mem::offset_of!(Example, sudoku) - 12usize];
};
