/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    pub fn fun_1(
        x: ::std::os::raw::c_int,
        xs: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
pub type triple = [::std::os::raw::c_int; 3usize];
unsafe extern "C" {
    pub fn fun_2(xs: *mut ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
