/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    /** Conflicting attributes on functions for llvm/clang versions 18 and up

 Examples from https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html*/
    pub fn square_cp(x: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn square_pc(x: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn square_cc(x: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn square_pp(x: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
