/* automatically generated by rust-bindgen 0.71.1 */

pub type FILE = ::std::os::raw::c_int;
unsafe extern "C" {
    pub static stdin: *mut FILE;
}
unsafe extern "C" {
    pub static stdout: *mut FILE;
}
unsafe extern "C" {
    pub static stderr: *mut FILE;
}
