/* automatically generated by rust-bindgen 0.70.1 */

extern "C" {
    pub fn capi();
}
extern "C" {
    pub fn ccall();
}
extern "C" {
    pub fn interruptible();
}
extern "C" {
    pub fn javascript();
}
extern "C" {
    pub fn prim();
}
extern "C" {
    pub fn safe();
}
extern "C" {
    pub fn stdcall();
}
extern "C" {
    #[link_name = "\u{1}unsafe"]
    pub fn unsafe_();
}
extern "C" {
    pub fn using();
}
extern "C" {
    pub fn via();
}
