/* automatically generated by rust-bindgen 0.70.1 */

extern "C" {
    pub fn by();
}
extern "C" {
    pub fn forall();
}
extern "C" {
    pub fn mdo();
}
extern "C" {
    pub fn pattern();
}
extern "C" {
    #[link_name = "\u{1}proc"]
    pub fn proc_();
}
extern "C" {
    pub fn rec();
}
extern "C" {
    pub fn using();
}
extern "C" {
    pub fn anyclass();
}
extern "C" {
    pub fn capi();
}
extern "C" {
    pub fn cases();
}
extern "C" {
    pub fn ccall();
}
extern "C" {
    pub fn dynamic();
}
extern "C" {
    pub fn export();
}
extern "C" {
    pub fn family();
}
extern "C" {
    pub fn group();
}
extern "C" {
    pub fn interruptible();
}
extern "C" {
    pub fn javascript();
}
extern "C" {
    pub fn label();
}
extern "C" {
    pub fn prim();
}
extern "C" {
    pub fn role();
}
extern "C" {
    pub fn safe();
}
extern "C" {
    pub fn stdcall();
}
extern "C" {
    pub fn stock();
}
extern "C" {
    #[link_name = "\u{1}unsafe"]
    pub fn unsafe_();
}
extern "C" {
    pub fn via();
}
