/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_FILE {
    _unused: [u8; 0],
}
pub type FILE = _IO_FILE;
pub type time_t = ::std::os::raw::c_long;
pub const FileOperationStatus_SUCCESS: FileOperationStatus = 0;
pub const FileOperationStatus_NOT_FOUND: FileOperationStatus = 2;
pub const FileOperationStatus_PERMISSION_DENIED: FileOperationStatus = 13;
pub const FileOperationStatus_INVALID_ARGUMENT: FileOperationStatus = 22;
pub const FileOperationStatus_OUT_OF_MEMORY: FileOperationStatus = 12;
pub const FileOperationStatus_CUSTOM_ERROR_OTHER: FileOperationStatus = -1;
pub type FileOperationStatus = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FileOperationRecord {
    pub status: FileOperationStatus,
    pub bytes_processed: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of FileOperationRecord",
    ][::std::mem::size_of::<FileOperationRecord>() - 16usize];
    [
        "Alignment of FileOperationRecord",
    ][::std::mem::align_of::<FileOperationRecord>() - 8usize];
    [
        "Offset of field: FileOperationRecord::status",
    ][::std::mem::offset_of!(FileOperationRecord, status) - 0usize];
    [
        "Offset of field: FileOperationRecord::bytes_processed",
    ][::std::mem::offset_of!(FileOperationRecord, bytes_processed) - 8usize];
};
unsafe extern "C" {
    pub fn read_file_chunk(
        file_ptr: *mut FILE,
        buffer: *mut ::std::os::raw::c_void,
        bytes_to_read: usize,
    ) -> FileOperationStatus;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct UnselectedStruct {
    pub time_t_should_not_be_in_fixtures: time_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of UnselectedStruct"][::std::mem::size_of::<UnselectedStruct>() - 8usize];
    [
        "Alignment of UnselectedStruct",
    ][::std::mem::align_of::<UnselectedStruct>() - 8usize];
    [
        "Offset of field: UnselectedStruct::time_t_should_not_be_in_fixtures",
    ][::std::mem::offset_of!(UnselectedStruct, time_t_should_not_be_in_fixtures)
        - 0usize];
};
