/* automatically generated by rust-bindgen 0.70.1 */

extern "C" {
    pub fn erf(arg: f64) -> f64;
}
extern "C" {
    pub fn no_args();
}
extern "C" {
    pub fn fun(x: ::std::os::raw::c_char, y: f64) -> ::std::os::raw::c_int;
}
