/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    pub fn erf(arg: f64) -> f64;
}
unsafe extern "C" {
    pub fn no_args();
}
unsafe extern "C" {
    pub fn no_args_no_void();
}
unsafe extern "C" {
    pub fn fun(x: ::std::os::raw::c_char, y: f64) -> ::std::os::raw::c_int;
}
