/* automatically generated by rust-bindgen 0.70.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct thing {
    pub x: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of thing"][::std::mem::size_of::<thing>() - 4usize];
    ["Alignment of thing"][::std::mem::align_of::<thing>() - 4usize];
    ["Offset of field: thing::x"][::std::mem::offset_of!(thing, x) - 0usize];
};
extern "C" {
    pub fn thing_fun_1(x: thing) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn thing_fun_2(x: ::std::os::raw::c_int) -> thing;
}
