/* automatically generated by rust-bindgen 0.71.1 */

pub type myint = ::std::os::raw::c_int;
pub type intptr = *mut ::std::os::raw::c_int;
pub type FunctionPointer_Function = ::std::option::Option<unsafe extern "C" fn()>;
pub type NonFunctionPointer_Function = ::std::option::Option<
    unsafe extern "C" fn(value: ::std::os::raw::c_int) -> ::std::os::raw::c_int,
>;
