/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    pub static a: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut b: *const ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static c: *mut ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static d: *const ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn list_example(items: *mut *const ::std::os::raw::c_char, count: usize) -> bool;
}
