/* automatically generated by rust-bindgen 0.70.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vector {
    pub x: f64,
    pub y: f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vector"][::std::mem::size_of::<vector>() - 16usize];
    ["Alignment of vector"][::std::mem::align_of::<vector>() - 8usize];
    ["Offset of field: vector::x"][::std::mem::offset_of!(vector, x) - 0usize];
    ["Offset of field: vector::y"][::std::mem::offset_of!(vector, y) - 8usize];
};
extern "C" {
    pub fn new_vector(x: f64, y: f64) -> *mut vector;
}
