/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    pub fn f0();
}
unsafe extern "C" {
    pub fn f1();
}
unsafe extern "C" {
    pub fn f5();
}
unsafe extern "C" {
    pub fn f6();
}
unsafe extern "C" {
    pub fn f10();
}
unsafe extern "C" {
    pub fn f11();
}
unsafe extern "C" {
    pub fn f15();
}
unsafe extern "C" {
    pub fn f16();
}
unsafe extern "C" {
    pub static mut i0: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i1: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i2: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i3: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i4: ::std::os::raw::c_int;
}
pub const i5: ::std::os::raw::c_int = 5;
pub const i6: ::std::os::raw::c_int = 6;
pub const i7: ::std::os::raw::c_int = 7;
pub const i8_: ::std::os::raw::c_int = 8;
pub const i9: ::std::os::raw::c_int = 9;
unsafe extern "C" {
    pub static mut i10: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i11: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i12: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i13: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i14: ::std::os::raw::c_int;
}
pub const i15: ::std::os::raw::c_int = 15;
pub const i16_: ::std::os::raw::c_int = 16;
pub const i17: ::std::os::raw::c_int = 17;
pub const i18: ::std::os::raw::c_int = 18;
pub const i19: ::std::os::raw::c_int = 19;
unsafe extern "C" {
    pub static mut i20: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i21: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i22: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i23: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i24: ::std::os::raw::c_int;
}
pub const i25: ::std::os::raw::c_int = 25;
pub const i26: ::std::os::raw::c_int = 26;
pub const i27: ::std::os::raw::c_int = 27;
pub const i28: ::std::os::raw::c_int = 28;
pub const i29: ::std::os::raw::c_int = 29;
