/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    /** Visibility attributes on functions

 https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-visibility-function-attribute*/
    pub fn f0();
}
unsafe extern "C" {
    pub fn f1();
}
unsafe extern "C" {
    pub static mut i0: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i1: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i2: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i3: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i4: ::std::os::raw::c_int;
}
