/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    pub fn f0();
}
unsafe extern "C" {
    pub fn f1();
}
unsafe extern "C" {
    pub fn f5();
}
unsafe extern "C" {
    pub fn f6();
}
unsafe extern "C" {
    pub static mut i0: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i1: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i2: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i3: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i4: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i5: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i6: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i7: ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[link_name = "\u{1}i8"]
    pub static mut i8_: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i9: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i10: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i11: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i12: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i13: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut i14: ::std::os::raw::c_int;
}
