/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _bindgen_ty_1 {
    pub foo: ::std::os::raw::c_int,
    pub bar: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _bindgen_ty_1"][::std::mem::size_of::<_bindgen_ty_1>() - 8usize];
    ["Alignment of _bindgen_ty_1"][::std::mem::align_of::<_bindgen_ty_1>() - 4usize];
    [
        "Offset of field: _bindgen_ty_1::foo",
    ][::std::mem::offset_of!(_bindgen_ty_1, foo) - 0usize];
    [
        "Offset of field: _bindgen_ty_1::bar",
    ][::std::mem::offset_of!(_bindgen_ty_1, bar) - 4usize];
};
