/* automatically generated by rust-bindgen 0.71.1 */

pub type ParsedAndNotSelected = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PossiblyNotParsedDefinitelyNotSelected {
    pub x: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of PossiblyNotParsedDefinitelyNotSelected",
    ][::std::mem::size_of::<PossiblyNotParsedDefinitelyNotSelected>() - 4usize];
    [
        "Alignment of PossiblyNotParsedDefinitelyNotSelected",
    ][::std::mem::align_of::<PossiblyNotParsedDefinitelyNotSelected>() - 4usize];
    [
        "Offset of field: PossiblyNotParsedDefinitelyNotSelected::x",
    ][::std::mem::offset_of!(PossiblyNotParsedDefinitelyNotSelected, x) - 0usize];
};
pub type ParsedAndSelected1 = ::std::os::raw::c_int;
pub type ParsedAndSelected2 = ParsedAndNotSelected;
pub type ParsedAndSelected3 = PossiblyNotParsedDefinitelyNotSelected;
