exclude_path = [
  # skip submodules, because we are only interested in checking links in our own
  # documentation.
  "alternatives/tools/c2hs",
  "alternatives/tools/hsc2hs",
  "examples/botan/botan",
  "examples/c-minisat/minisat-c-bindings",
  "examples/c-qrcode/QR-Code-generator",
  "examples/c-rogueutil/rogueuti",
  "examples/c-rpm/rpm",
  # copied from .gitignore because lychee does not respect .gitignore when
  # passed globs (see https://github.com/lycheeverse/lychee/discussions/1612).
  "dist-newstyle*",
]