exclude_path = [
  # skip third-party sources fetched on demand by the example scripts, because
  # we are only interested in checking links in our own documentation.
  "examples/botan/botan",
  "examples/c-minisat/minisat-c-bindings",
  "examples/c-qrcode/QR-Code-generator",
  "examples/c-rogueutil/rogueutil",
  "examples/c-rpm/rpm",
  "examples/c-yaml/yaml",
  "examples/cef/cef_binary*",
  "examples/libgit2/libgit2",
  "examples/libpcap/libpcap",
  "examples/libsodium/libsodium",
  # copied from .gitignore because lychee does not respect .gitignore when
  # passed globs (see https://github.com/lycheeverse/lychee/discussions/1612).
  "dist-newstyle*",
]

accept = ["100..=103", "200..=299", 502]
