cabal-version: 3.0
name:          constructor-import-issue
version:       0.1.0
license:       BSD-3-Clause
license-file:  LICENSE
author:        Well-Typed LLP
maintainer:    info@well-typed.com
build-type:    Simple

common lang
  build-depends:    base >=4.17 && <5
  default-language: GHC2021
  ghc-options:      -Wall -Wunused-packages

executable constructor-import-issue-bin
  import:          lang
  main-is:         Main.hs
  hs-source-dirs:  app generated
  extra-libraries: constructor_import_issue
  build-depends:   hs-bindgen-runtime
  other-modules:
    Generated.NoStdlib.A
    Generated.NoStdlib.B
    Generated.NoStdlib.C
    Generated.NoStdlib.C.FunPtr
    Generated.NoStdlib.C.Global
    Generated.NoStdlib.C.Safe
    Generated.NoStdlib.C.Unsafe
    Generated.Stdlib.A
    Generated.Stdlib.B
    Generated.Stdlib.C
    Generated.Stdlib.C.FunPtr
    Generated.Stdlib.C.Global
    Generated.Stdlib.C.Safe
    Generated.Stdlib.C.Unsafe
