name: Setup git
description: Configure git to use LF line endings and fix macOS git

runs:
  using: composite
  steps:
  - name: Set git to use LF
    shell: bash
    run: |
      git config --global core.autocrlf false
      git config --global core.eol lf

  - name: Fix git on macOS (prioritize system git over Homebrew)
    shell: bash
    if: ${{ runner.os == 'macOS' }}
    run: |
      echo "/usr/bin" >> "$GITHUB_PATH"
