/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct foo {
    pub sixty_four: u64,
    pub thirty_two: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of foo"][::std::mem::size_of::<foo>() - 16usize];
    ["Alignment of foo"][::std::mem::align_of::<foo>() - 8usize];
    [
        "Offset of field: foo::sixty_four",
    ][::std::mem::offset_of!(foo, sixty_four) - 0usize];
    [
        "Offset of field: foo::thirty_two",
    ][::std::mem::offset_of!(foo, thirty_two) - 8usize];
};
