name: Manual (Ubuntu)
description: Build and run the manual on Ubuntu

# If needed, we can SSH into the machine executing the job and
# figure out what's going on:
# - name: Setup tmate session
#   uses: mxschmitt/action-tmate@v3

runs:
  using: composite
  steps:
    # Ubuntu doesn't have an issue with Unicode characters. Note also that we
    # are passing '-DSUPPORTS_UNICODE' this option passes SUPPORTS_UNICODE macro
    # to libclang preprocessor.
    - name: Configure environment variables
      shell: bash
      run: |
        export BINDGEN_EXTRA_CLANG_ARGS=-DSUPPORTS_UNICODE
        echo "BINDGEN_EXTRA_CLANG_ARGS=$BINDGEN_EXTRA_CLANG_ARGS" >> "$GITHUB_ENV"

    - name: Create cabal.project in ./manual/hs
      shell: bash
      working-directory: ./manual/hs
      run: cp cabal.project.ci cabal.project

    - name: Generate bindings, build and run the manual
      shell: bash
      working-directory: ./manual
      run: ./generate-and-run.sh
