/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    ///! Global, complete, initialised
    pub static mut arr1: [::std::os::raw::c_int; 1usize];
}
unsafe extern "C" {
    ///! Global, extern, complete, not initialised
    pub static mut arr2: [::std::os::raw::c_int; 3usize];
}
unsafe extern "C" {
    ///! Global, extern, incomplete
    pub static mut arr3: [::std::os::raw::c_int; 0usize];
}
unsafe extern "C" {
    ///! Multi-dimensional array of known size.
    pub static mut sudoku: [[::std::os::raw::c_int; 3usize]; 3usize];
}
unsafe extern "C" {
    /**! Multi-dimensional array of unknown size. Only the first dimension is allowed
! to be unknown.*/
    pub static mut triplets: [[::std::os::raw::c_int; 3usize]; 0usize];
}
pub type triplet = [::std::os::raw::c_int; 3usize];
pub type matrix = [triplet; 3usize];
unsafe extern "C" {
    pub fn transpose(input: *const triplet, output: *mut triplet);
}
/**! A typedef representing a an array of unknown size, where each element is a
! pointer to an array of known size 3, where each element is an int.*/
pub type triplet_ptrs = [*mut [::std::os::raw::c_int; 3usize]; 0usize];
unsafe extern "C" {
    ///! A global of triplet_ptrs
    pub static mut global_triplet_ptrs: triplet_ptrs;
}
unsafe extern "C" {
    ///! A function that prints the given triplet_ptrs
    pub fn pretty_print_triplets(x: *mut *mut [::std::os::raw::c_int; 3usize]);
}
