/* automatically generated by rust-bindgen 0.71.1 */

pub const i1: ::std::os::raw::c_int = 1;
pub const i2: ::std::os::raw::c_int = 3;
unsafe extern "C" {
    pub static mut i3: ::std::os::raw::c_int;
}
