name: Manual (Windows)
description: Build and run the manual on Windows

# If needed, we can SSH into the machine executing the job and
# figure out what's going on:
# - name: Setup tmate session
#   uses: mxschmitt/action-tmate@v3

runs:
  using: composite
  steps:
    # Environment variables:
    #
    # * Windows assembler has an issue with Unicode characters so we don't set
    #   SUPPORTS_UNICODE flag
    #
    #   In `manual_examples.{c,h}` and `manual/hs/app/RunManual.hs` we have CPP
    #   clauses to replace the 拜拜 and ϒ functions by ByeBye and Gamma. The
    #   former, because LLVM itermediate representation (IR) does not support
    #   Unicode characters and the latter because Apple's assembler also does
    #   not support Unicode characters.
    #
    # * We need to add `manual/c` to the PATH. The dynamic-link library search
    #   order indicates that it searches directories listed in PATH for DLLs as
    #   a last resort. When we run the manual, this PATH setting is what allows
    #   it to find the required DLLs.
    - name: Configure environment variables
      shell: bash
      run: |
        echo "${{github.workspace}}\\manual\\c" >> "$GITHUB_PATH"

    # Note that -DSUPPORTS_UNICODE is not set because Windows assembler
    # doesn't support Unicode characters.
    - name: Create cabal.project.local
      shell: bash
      working-directory: ./manual/hs
      run: |
        echo "Writing cabal.project.local to configure C paths..."
        cat <<EOF > cabal.project.local
        -- The index state should match `cabal.project.ci` on top level.
        index-state: 2025-09-16T04:55:58Z

        package manual
          extra-include-dirs:
              ${{ github.workspace }}\\manual\\c
          extra-lib-dirs:
              ${{ github.workspace }}\\manual\\c

        package hs-game
          extra-include-dirs:
              ${{ github.workspace }}\\manual\\c
          extra-lib-dirs:
              ${{ github.workspace }}\\manual\\c

        package hs-vector
          extra-include-dirs:
              ${{ github.workspace }}\\manual\\c
          extra-lib-dirs:
              ${{ github.workspace }}\\manual\\c
        EOF

    - name: Build the C libraries
      shell: bash
      working-directory: ./manual/c
      run: make

    - name: Run binding generation script
      shell: bash
      working-directory: ./manual
      run: ./generate.sh

    - name: Build the manual
      shell: bash
      working-directory: ./manual/hs
      run: cabal build all

    - name: Run the manual executable
      shell: bash
      working-directory: ./manual/hs
      run: cabal run manual
