cabal-version:   3.0
name:            cef
version:         0.1.0.0
license:         BSD-3-Clause
license-file:    LICENSE
author:          Well-Typed LLP
maintainer:      info@well-typed.com
build-type:      Simple
extra-doc-files: CHANGELOG.md

common warnings
  ghc-options:
    -Wall -Wcompat -Wincomplete-uni-patterns
    -Wincomplete-record-updates -Wpartial-fields -Widentities
    -Wredundant-constraints -Wmissing-export-lists
    -Wno-unticked-promoted-constructors -Wunused-packages
    -Wmissing-deriving-strategies

common language
  default-language:   GHC2021
  default-extensions:
    DerivingStrategies
    ImportQualifiedPost
    LambdaCase
    PatternSynonyms
    RecordWildCards
    RoleAnnotations
    ViewPatterns

library
  import:          warnings, language
  exposed-modules:
    CEF.Cef_accessibility_handler_capi
    CEF.Cef_api_hash
    CEF.Cef_api_hash.FunPtr
    CEF.Cef_api_hash.Safe
    CEF.Cef_api_hash.Unsafe
    CEF.Cef_app_capi
    CEF.Cef_app_capi.FunPtr
    CEF.Cef_app_capi.Safe
    CEF.Cef_app_capi.Unsafe
    CEF.Cef_audio_handler_capi
    CEF.Cef_auth_callback_capi
    CEF.Cef_base_capi
    CEF.Cef_browser_capi
    CEF.Cef_browser_capi.FunPtr
    CEF.Cef_browser_capi.Safe
    CEF.Cef_browser_capi.Unsafe
    CEF.Cef_browser_process_handler_capi
    CEF.Cef_callback_capi
    CEF.Cef_client_capi
    CEF.Cef_command_handler_capi
    CEF.Cef_command_line_capi
    CEF.Cef_command_line_capi.FunPtr
    CEF.Cef_command_line_capi.Safe
    CEF.Cef_command_line_capi.Unsafe
    CEF.Cef_context_menu_handler_capi
    CEF.Cef_cookie_capi
    CEF.Cef_cookie_capi.FunPtr
    CEF.Cef_cookie_capi.Safe
    CEF.Cef_cookie_capi.Unsafe
    CEF.Cef_crash_util_capi
    CEF.Cef_crash_util_capi.FunPtr
    CEF.Cef_crash_util_capi.Safe
    CEF.Cef_crash_util_capi.Unsafe
    CEF.Cef_devtools_message_observer_capi
    CEF.Cef_dialog_handler_capi
    CEF.Cef_display_handler_capi
    CEF.Cef_dom_capi
    CEF.Cef_download_handler_capi
    CEF.Cef_download_item_capi
    CEF.Cef_drag_data_capi
    CEF.Cef_drag_data_capi.FunPtr
    CEF.Cef_drag_data_capi.Safe
    CEF.Cef_drag_data_capi.Unsafe
    CEF.Cef_drag_handler_capi
    CEF.Cef_file_util_capi
    CEF.Cef_file_util_capi.FunPtr
    CEF.Cef_file_util_capi.Safe
    CEF.Cef_file_util_capi.Unsafe
    CEF.Cef_find_handler_capi
    CEF.Cef_focus_handler_capi
    CEF.Cef_frame_capi
    CEF.Cef_frame_handler_capi
    CEF.Cef_i18n_util_capi.FunPtr
    CEF.Cef_i18n_util_capi.Safe
    CEF.Cef_i18n_util_capi.Unsafe
    CEF.Cef_image_capi
    CEF.Cef_image_capi.FunPtr
    CEF.Cef_image_capi.Safe
    CEF.Cef_image_capi.Unsafe
    CEF.Cef_jsdialog_handler_capi
    CEF.Cef_keyboard_handler_capi
    CEF.Cef_life_span_handler_capi
    CEF.Cef_load_handler_capi
    CEF.Cef_media_router_capi
    CEF.Cef_media_router_capi.FunPtr
    CEF.Cef_media_router_capi.Safe
    CEF.Cef_media_router_capi.Unsafe
    CEF.Cef_menu_model_capi
    CEF.Cef_menu_model_capi.FunPtr
    CEF.Cef_menu_model_capi.Safe
    CEF.Cef_menu_model_capi.Unsafe
    CEF.Cef_menu_model_delegate_capi
    CEF.Cef_navigation_entry_capi
    CEF.Cef_origin_whitelist_capi
    CEF.Cef_origin_whitelist_capi.FunPtr
    CEF.Cef_origin_whitelist_capi.Safe
    CEF.Cef_origin_whitelist_capi.Unsafe
    CEF.Cef_parser_capi
    CEF.Cef_parser_capi.FunPtr
    CEF.Cef_parser_capi.Safe
    CEF.Cef_parser_capi.Unsafe
    CEF.Cef_path_util_capi
    CEF.Cef_path_util_capi.FunPtr
    CEF.Cef_path_util_capi.Safe
    CEF.Cef_path_util_capi.Unsafe
    CEF.Cef_permission_handler_capi
    CEF.Cef_preference_capi
    CEF.Cef_preference_capi.FunPtr
    CEF.Cef_preference_capi.Safe
    CEF.Cef_preference_capi.Unsafe
    CEF.Cef_print_handler_capi
    CEF.Cef_print_settings_capi
    CEF.Cef_print_settings_capi.FunPtr
    CEF.Cef_print_settings_capi.Safe
    CEF.Cef_print_settings_capi.Unsafe
    CEF.Cef_process_message_capi
    CEF.Cef_process_message_capi.FunPtr
    CEF.Cef_process_message_capi.Safe
    CEF.Cef_process_message_capi.Unsafe
    CEF.Cef_process_util_capi
    CEF.Cef_registration_capi
    CEF.Cef_render_handler_capi
    CEF.Cef_render_process_handler_capi
    CEF.Cef_request_capi
    CEF.Cef_request_capi.FunPtr
    CEF.Cef_request_capi.Safe
    CEF.Cef_request_capi.Unsafe
    CEF.Cef_request_context_capi
    CEF.Cef_request_context_capi.FunPtr
    CEF.Cef_request_context_capi.Safe
    CEF.Cef_request_context_capi.Unsafe
    CEF.Cef_request_context_handler_capi
    CEF.Cef_request_handler_capi
    CEF.Cef_resource_bundle_capi
    CEF.Cef_resource_bundle_capi.FunPtr
    CEF.Cef_resource_bundle_capi.Safe
    CEF.Cef_resource_bundle_capi.Unsafe
    CEF.Cef_resource_bundle_handler_capi
    CEF.Cef_resource_handler_capi
    CEF.Cef_resource_request_handler_capi
    CEF.Cef_response_capi
    CEF.Cef_response_capi.FunPtr
    CEF.Cef_response_capi.Safe
    CEF.Cef_response_capi.Unsafe
    CEF.Cef_response_filter_capi
    CEF.Cef_scheme_capi
    CEF.Cef_scheme_capi.FunPtr
    CEF.Cef_scheme_capi.Safe
    CEF.Cef_scheme_capi.Unsafe
    CEF.Cef_server_capi
    CEF.Cef_server_capi.FunPtr
    CEF.Cef_server_capi.Safe
    CEF.Cef_server_capi.Unsafe
    CEF.Cef_shared_memory_region_capi
    CEF.Cef_shared_process_message_builder_capi
    CEF.Cef_shared_process_message_builder_capi.FunPtr
    CEF.Cef_shared_process_message_builder_capi.Safe
    CEF.Cef_shared_process_message_builder_capi.Unsafe
    CEF.Cef_ssl_info_capi
    CEF.Cef_ssl_info_capi.FunPtr
    CEF.Cef_ssl_info_capi.Safe
    CEF.Cef_ssl_info_capi.Unsafe
    CEF.Cef_ssl_status_capi
    CEF.Cef_stream_capi
    CEF.Cef_stream_capi.FunPtr
    CEF.Cef_stream_capi.Safe
    CEF.Cef_stream_capi.Unsafe
    CEF.Cef_string_visitor_capi
    CEF.Cef_task_capi
    CEF.Cef_task_capi.FunPtr
    CEF.Cef_task_capi.Safe
    CEF.Cef_task_capi.Unsafe
    CEF.Cef_task_manager_capi
    CEF.Cef_task_manager_capi.FunPtr
    CEF.Cef_task_manager_capi.Safe
    CEF.Cef_task_manager_capi.Unsafe
    CEF.Cef_thread_capi
    CEF.Cef_thread_capi.FunPtr
    CEF.Cef_thread_capi.Safe
    CEF.Cef_thread_capi.Unsafe
    CEF.Cef_trace_capi
    CEF.Cef_trace_capi.FunPtr
    CEF.Cef_trace_capi.Safe
    CEF.Cef_trace_capi.Unsafe
    CEF.Cef_unresponsive_process_callback_capi
    CEF.Cef_urlrequest_capi
    CEF.Cef_urlrequest_capi.FunPtr
    CEF.Cef_urlrequest_capi.Safe
    CEF.Cef_urlrequest_capi.Unsafe
    CEF.Cef_v8_capi
    CEF.Cef_v8_capi.FunPtr
    CEF.Cef_v8_capi.Safe
    CEF.Cef_v8_capi.Unsafe
    CEF.Cef_values_capi
    CEF.Cef_values_capi.FunPtr
    CEF.Cef_values_capi.Safe
    CEF.Cef_values_capi.Unsafe
    CEF.Cef_version_info
    CEF.Cef_version_info.FunPtr
    CEF.Cef_version_info.Safe
    CEF.Cef_version_info.Unsafe
    CEF.Cef_waitable_event_capi
    CEF.Cef_waitable_event_capi.FunPtr
    CEF.Cef_waitable_event_capi.Safe
    CEF.Cef_waitable_event_capi.Unsafe
    CEF.Cef_x509_certificate_capi
    CEF.Cef_xml_reader_capi
    CEF.Cef_xml_reader_capi.FunPtr
    CEF.Cef_xml_reader_capi.Safe
    CEF.Cef_xml_reader_capi.Unsafe
    CEF.Cef_zip_reader_capi
    CEF.Cef_zip_reader_capi.FunPtr
    CEF.Cef_zip_reader_capi.Safe
    CEF.Cef_zip_reader_capi.Unsafe

  build-depends:
    , base
    , hs-bindgen-runtime

  hs-source-dirs:  src
  extra-libraries: cef
  ghc-options:     -Wno-missing-export-lists

executable cef-bin
  import:         warnings, language
  main-is:        Main.hs
  build-depends:
    , base
    , cef
    , hs-bindgen-runtime

  hs-source-dirs: app
