module Second where

import Foreign.Marshal.Alloc (alloca)
import Foreign.Storable (peek)
import Optics ((%), (&), (.~))

import HsBindgen.Runtime.LibC qualified
import HsBindgen.TH

import First -- import FirstHandle

-- Pin FirstHandle (from first.h) to the type already generated by First, so
-- this splice references it instead of generating its own copy.
let cfg :: Config
    cfg = def
      & #clang % #extraIncludeDirs .~ [Pkg "cbits"]
      & #bindingSpec % #extBindingSpecs .~ ["first-ext.yaml"]
    cfgTh :: ConfigTH
    cfgTh = def
 in withHsBindgen cfg cfgTh $
      hashInclude "second.h"

initialize :: FirstHandle -> IO SecondHandle
initialize firstHandle = alloca $ \pHandle -> do
  initSecondHandle firstHandle pHandle
  peek pHandle
