name: Base
description: Build and test `hs-bindgen`, build and run manual

inputs:
  runner:
    description: 'The used runner'
    required: true
  ghc:
    description: ""
    required: true
  llvm:
    description: 'LLVM version'
    required: true
  build-with-old-versions:
    description: 'Build with --prefer-oldest to test lower bounds'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup Haskell
      id: setup-haskell
      uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ inputs.ghc }}
        cabal-version: 3.16

    - name: Debug (Haskell)
      shell: bash
      run: |
        echo '### ghc --version'
        ghc --version
        echo '### ghc-pkg list'
        ghc-pkg list
        echo '### ghc --info'
        ghc --info

    - name: Install LLVM/Clang
      uses: ./.github/actions/setup-llvm
      with:
        version: ${{ inputs.llvm }}

    - name: cabal.project
      shell: bash
      run: cp cabal.project.ci cabal.project

    - name: Windows quirks - Configure environment for libclang
      shell: bash
      if: ${{ startsWith(inputs.runner, 'windows') }}
      run: |
        # Set library path for linker to find import libraries (.lib files)
        echo "LIBRARY_PATH=$LLVM_PATH/lib" >> "$GITHUB_ENV"

        echo "$LLVM_PATH/lib" >> "$GITHUB_PATH"
        echo "$LLVM_PATH/bin" >> "$GITHUB_PATH"

    - name: Dry build (for cache key)
      shell: bash
      run: cabal build all --dry-run

    - name: Restore cache
      id: cache-cabal-restore
      uses: actions/cache/restore@v4
      env:
        key: build-and-test-${{ inputs.runner }}-ghc-${{ steps.setup-haskell.outputs.ghc-version }}-cabal-${{ steps.setup-haskell.outputs.cabal-version }}-llvm-${{ inputs.llvm}}
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ env.key }}-plan-${{ hashFiles('dist-newstyle/cache/plan.json') }}
        restore-keys: ${{ env.key }}-

    - name: Build (prefer oldest) - test lower bounds
      shell: bash
      if: ${{ inputs.build-with-old-versions == 'true' }}
      run: cabal build all --prefer-oldest

    - name: Dependencies
      shell: bash
      run: cabal build all --only-dependencies -j4

    - name: Build
      shell: bash
      run: cabal build all -j4

    - name: Debug (hs-bindgen)
      shell: bash
      run: |
        echo '### Version'
        cabal run hs-bindgen-cli -- --version
        echo '### libclang -v'
        cabal run hs-bindgen-cli -- info libclang --clang-option=-v
        echo '### Resolve (clang)'
        cabal run hs-bindgen-cli -- info resolve-header -v4 --builtin-include-dir=clang stdint.h

    - name: Test
      shell: bash
      run: cabal test all --test-show-details=direct

    - name: Build manual (macOS)
      if: runner.os == 'macOS'
      uses: ./.github/actions/build-manual-macos

    - name: Build manual (Ubuntu)
      if: runner.os == 'Linux'
      uses: ./.github/actions/build-manual-ubuntu

    - name: Build manual (Windows)
      if: runner.os == 'Windows'
      uses: ./.github/actions/build-manual-windows

    # Save the cache after building the project AND the manual.
    - name: Save cache
      uses: actions/cache/save@v4
      # Even save the cache, even when a previous job failed. Do not save the
      # cache when the job gets canceled.
      if: ${{ !cancelled() }}
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ steps.cache-cabal-restore.outputs.cache-primary-key }}
