name: Bundled C example
description: Build and run the bundled C example

runs:
  using: composite
  steps:
    - name: Run generation and build script
      shell: bash
      working-directory: ./examples/bundled-c
      run: ./generate-and-run.sh

    - name: Test CPP flag mismatch detection
      shell: bash
      working-directory: ./examples/bundled-c
      run: ./test-cpp-mismatch.sh
