-- | Batch compilation of TH fixture modules via @cabal build@
--
module Test.HsBindgen.THFixtures.Compile (
    setupBatchCompile
  , sanitizeLibName
  ) where

import Control.Monad (guard)
import Data.Char (isAlphaNum, isDigit)
import Data.List (isInfixOf, stripPrefix)
import Data.Map.Strict (Map)
import Data.Map.Strict qualified as Map
import Data.Set (Set)
import Data.Set qualified as Set
import System.Directory (createDirectoryIfMissing)
import System.Exit (ExitCode (..))
import System.FilePath ((</>))
import System.IO.Temp (withSystemTempDirectory)
import System.Process (CreateProcess (cwd), proc, readCreateProcessWithExitCode)

{-------------------------------------------------------------------------------
  Setup
-------------------------------------------------------------------------------}

-- | Set up batch compilation
--
-- 1. Create temp dir
-- 2. Write all TH modules to subdirectories
-- 3. Generate hs-bindgen-th-fixtures.cabal with one internal library per test
-- 4. Generate self-contained cabal.project
-- 5. Run @cabal build --keep-going@
-- 6. Parse "Failed to build" lines to determine per-library success/failure
--
setupBatchCompile
  :: FilePath            -- ^ Repo root (parent of hs-bindgen/)
  -> [(String, String)]  -- ^ (test name, module content)
  -> IO (Map String (Either String ()))
setupBatchCompile repoRoot cases =
    withSystemTempDirectory "hs-bindgen-th-fixtures" $ \tmpDir -> do
      -- Write each module into its own subdirectory
      mapM_ (writeTestModule tmpDir) cases

      -- Generate cabal file and project
      let libNames = map (\(name, _) -> sanitizeLibName name) cases
          cabalContent = generateCabalFile repoRoot libNames
      writeFile (tmpDir </> "hs-bindgen-th-fixtures.cabal") cabalContent

      let projectContent = generateCabalProject repoRoot
      writeFile (tmpDir </> "cabal.project") projectContent

      -- Run cabal build --keep-going
      let cabalArgs =
            [ "build"
            , "hs-bindgen-th-fixtures"
            , "--keep-going"
            -- Attempt to avoid nondeterministic failures; see
            -- <https://github.com/well-typed/hs-bindgen/issues/1813>
            , "-j1"
            , "--builddir=" ++ repoRoot </> "dist-newstyle-th-fixtures"
            ]
          createProc = (proc "cabal" cabalArgs) { cwd = Just tmpDir }

      (exitCode, _stdout, stderr) <-
        readCreateProcessWithExitCode createProc ""

      -- Determine per-library results
      let failedLibs = parseFailedLibs stderr
          libSections = parseLibSections stderr
          allLibNames =
            [ "th-fixture-" ++ sanitizeLibName name
            | (name, _) <- cases
            ]
          result libName
            | ExitSuccess <- exitCode       = Right ()
            | Set.null failedLibs           = Left stderr
            | Set.member libName failedLibs =
                Left $ Map.findWithDefault stderr libName libSections
            | otherwise                     = Right ()

      return $ Map.fromList
        [ (libName, result libName)
        | libName <- allLibNames
        ]

{-------------------------------------------------------------------------------
  Module writing
-------------------------------------------------------------------------------}

-- | Write a test module into its subdirectory
writeTestModule :: FilePath -> (String, String) -> IO ()
writeTestModule tmpDir (name, content) = do
    let subDir = tmpDir </> sanitizeLibName name
        modulePath = subDir </> "Example.hs"
    createDirectoryIfMissing True subDir
    writeFile modulePath content

{-------------------------------------------------------------------------------
  Cabal file generation
-------------------------------------------------------------------------------}

-- | Generate the .cabal file content
generateCabalFile :: FilePath -> [String] -> String
generateCabalFile repoRoot libNames = unlines $ concat
    [ header
    , commonStanza
    , concatMap libraryStanza libNames
    ]
  where
    hsBindgenDir = repoRoot </> "hs-bindgen"

    header :: [String]
    header =
      [ "cabal-version: 3.0"
      , "name:          hs-bindgen-th-fixtures"
      , "version:       0.0.0"
      , "build-type:    Simple"
      , ""
      , "-- This file is generated by Test.HsBindgen.THFixtures.Compile"
      , "-- Do not edit manually."
      ]

    commonStanza :: [String]
    commonStanza =
      [ ""
      , "common th-fixture-common"
      , "  default-language: GHC2021"
      , "  ghc-options:"
      , "    -Wall"
      , "    -Wincomplete-uni-patterns"
      , "    -Wincomplete-record-updates"
      , "    -Wmissing-exported-signatures"
      , "    -Widentities"
      , "    -Wredundant-constraints"
      , "    -Wpartial-fields"
      , "    -Wcpp-undef"
      , "    -Wno-unused-matches"
      , "    -optc-std=gnu2x"
      , "    -optc-Wno-deprecated-declarations"
      , "    -optc-Wno-attributes"
      , "  build-depends:"
      , "    , base"
      , "    , hs-bindgen"
      , "    , hs-bindgen-runtime"
      , "    , c-expr-runtime"
      , "    , optics"
      , "  include-dirs:"
      , "    " ++ hsBindgenDir </> "examples"
      , "    " ++ hsBindgenDir </> "examples" </> "golden"
      , "    " ++ hsBindgenDir </> "musl-include" </> "x86_64"
      ]

    libraryStanza :: String -> [String]
    libraryStanza libName =
      [ ""
      , "library th-fixture-" ++ libName
      , "  import: th-fixture-common"
      , "  hs-source-dirs: " ++ libName
      , "  exposed-modules: Example"
      ]

{-------------------------------------------------------------------------------
  Cabal project generation
-------------------------------------------------------------------------------}

-- | Generate cabal.project content
--
-- Imports @cabal.project.base@ to pick up @index-state@,
-- @source-repository-package@ stanzas, and @allow-newer@ entries.
--
-- Uses @shared: False@ so cabal builds static libraries (archives of .o
-- files) instead of shared libraries.  This avoids linker failures from
-- unresolved C symbols in CAPI FFI stubs — we only need to verify that
-- compilation succeeds, not that linking against the actual C libraries works.
generateCabalProject :: FilePath -> String
generateCabalProject repoRoot = unlines
    [ "import: " ++ repoRoot </> "cabal.project.base"
    , "packages:"
    , "  ."
    , "  " ++ repoRoot </> "hs-bindgen"
    , "  " ++ repoRoot </> "hs-bindgen-runtime"
    , "  " ++ repoRoot </> "c-expr-runtime"
    , "  " ++ repoRoot </> "c-expr-dsl"
    , "allow-newer: all"
    , "package hs-bindgen-th-fixtures"
    , "  shared: False"
    ]

{-------------------------------------------------------------------------------
  Result parsing
-------------------------------------------------------------------------------}

-- | Split cabal build stderr into per-library sections
--
-- With @-j1@, libraries compile sequentially so their errors appear in order
-- in stderr.  Each library's GHC error references its source directory as
-- @\<dirname\>/Example.hs:line:col: error:@.  We call that line the "anchor".
--
-- The structure of stderr when two libraries (A and B) fail looks like:
--
-- @
--   Warning: ...                                  ← preamble (assigned to A)
--   Template Haskell error: ... header_a.h ...    ← TH diagnostic (preamble, assigned to A)
--   dirname-a\/Example.hs:1:1: error: [GHC-87897] ← ANCHOR for lib A
--       Exception when trying to run ...          ← continuation (indented)
--     |                                           ← continuation (indented)
--   1 | {-# LANGUAGE CApiFFI #-}                  ← continuation (digit-prefixed)
--     | ^                                         ← continuation (indented)
--                                                 ← blank (continuation)
--   Template Haskell error: ... header_b.h ...    ← TH diagnostic (preamble, assigned to B)
--   dirname-b\/Example.hs:1:1: error: [GHC-87897] ← ANCHOR for lib B
--       ...                                       ← continuation
--                                                 ← blank (continuation)
--   Error: [Cabal-7125]                           ← footer (dropped)
--   Failed to build lib:th-fixture-dirname-a ...  ← footer (dropped)
--   Failed to build lib:th-fixture-dirname-b ...  ← footer (dropped)
-- @
--
-- Each section is: accumulated preamble + anchor + continuation lines (blank,
-- indented, or digit-prefixed).  The footer after the last continuation has no
-- following anchor, so it is dropped.
--
parseLibSections :: String -> Map String String
parseLibSections stderr =
    Map.fromList
      [ ("th-fixture-" ++ name, unlines sectionLines)
      | (name, sectionLines) <- extractSections (lines stderr)
      ]

-- | Break stderr lines into named sections, one per library.
--
-- Lines are accumulated as a "preamble" until a GHC error anchor
-- (@\<dirname\>/Example.hs:line:col:@) is found; then the preamble,
-- anchor, and its continuation lines form that library's section.
--
extractSections :: [String] -> [(String, [String])]
extractSections = collect []
  where
    collect :: [String] -> [String] -> [(String, [String])]
    collect _preamble [] = []
    collect preamble (l : ls) = case anchorLibName l of
        Just name ->
          let (cont, rest) = span isContinuation ls
          in  (name, preamble ++ l : cont) : collect [] rest
        Nothing ->
          collect (preamble ++ [l]) ls

-- | Try to extract a library dirname from a GHC error anchor line.
--
-- Matches lines like @types-enums-foo\/Example.hs:1:1: error: ...@
-- and returns @\"types-enums-foo\"@.
anchorLibName :: String -> Maybe String
anchorLibName line = do
    let (dirname, rest) = break (== '/') line
    guard $ not (null dirname)
    guard $ all isDirNameChar dirname
    _ <- stripPrefix "/Example.hs:" rest
    pure dirname

-- | Characters allowed in a cabal library directory name.
isDirNameChar :: Char -> Bool
isDirNameChar c = isAlphaNum c || c == '-' || c == '_'

-- | Does this line continue a GHC error block?
--
-- Blank lines, indented lines, and line-number references
-- (e.g. @1 | {-# LANGUAGE ... #-}@) are continuations.
isContinuation :: String -> Bool
isContinuation []    = True
isContinuation (c:_) = c == ' ' || isDigit c

-- | Parse failed library names from cabal build stderr
--
-- Scans for lines containing "Failed to build" and extracts @lib:NAME@ from
-- each.
parseFailedLibs :: String -> Set String
parseFailedLibs = Set.fromList . concatMap extractLib . lines
  where
    extractLib :: String -> [String]
    extractLib line
      | "Failed to build" `isInfixOf` line
      , Just name <- findLibName line = [name]
      | otherwise = []

    findLibName :: String -> Maybe String
    findLibName [] = Nothing
    findLibName ('l':'i':'b':':':rest) = Just (takeWhile isLibNameChar rest)
    findLibName (_:rest) = findLibName rest

    isLibNameChar :: Char -> Bool
    isLibNameChar c = isAlphaNum c || c == '-' || c == '_'

{-------------------------------------------------------------------------------
  Name sanitization
-------------------------------------------------------------------------------}

-- | Sanitize test name for use as a cabal library name
--
-- Ports the @compile-fixtures.sh@ sanitize logic:
--
-- * @.DIGIT@ -> @vDIGIT@  (avoids version-like segments)
-- * @_DIGIT@ -> @nDIGIT@  (avoids version-like segments)
-- * Remaining @/@, @_@, @.@ -> @-@
--
sanitizeLibName :: String -> String
sanitizeLibName = go
  where
    go [] = []
    go ('.':c:rest)
      | c `elem` ['0'..'9'] = 'v' : c : go rest
    go ('_':c:rest)
      | c `elem` ['0'..'9'] = 'n' : c : go rest
    go ('/':rest) = '-' : go rest
    go ('_':rest) = '-' : go rest
    go ('.':rest) = '-' : go rest
    go (c:rest) = c : go rest
