{-# LANGUAGE CPP #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}

-- TODO: finish documentation, including a manual section

-- TODO: use Marshallable in ToFunPtr and FromFunPtr

-- TODO: use Marshallable in function _Deref newtypes

-- TODO: use Marshallable in foreign imports

module HsBindgen.Runtime.Marshallable (
    -- * Class
    Marshallable
  , MarshallableBaseType
  , toMarshallableBaseType
  , fromMarshallableBaseType
    -- ** Deriving-via
  , ViaNewtype (..)
  ) where

import Data.Int
import Data.Kind
import Data.Word
import Foreign.C.Error
import Foreign.C.Types
import Foreign.Ptr
import Foreign.StablePtr

#if MIN_VERSION_base(4, 18, 0)
import Foreign.C.ConstPtr
#endif

{- $foreign-types

The 'Marshallable' class broadly captures Haskell types that are marshallable
through the FFI. By marshallable we mean: types that are valid in a foreign
import. The "Haskell 2010 Language" report provides grammars for types that are
considered marshallable. These grammars include:

* /basic foreign types/ (technically not specified as a proper pgrammar)
* /foreign types/
* /marshallable foreign result types/
* /marshallable foreign types/

See the "8.4.2 Foreign Types" section of the report for more information:
<https://www.haskell.org/onlinereport/haskell2010/haskellch8.html#x15-1560008.4.2>

This module comes with 'Marshallable' instances for the rules in these grammars,
plus additional instances for types from @base@ that are not described in the
report as being marshallable, such as types from the "Foreign.C.Types" module.

=== Soundness and completeness

In the report, the grammars for marshallable types are separate. In our
'Marshallable' class, we conflate these grammars for the sake of simplicity,
because it is complex to encode the grammars into separate classes precisely.
This has the caveat that the class and the default instances provided in this
module are not /sound/ with respect to marshallable types as described in the
Haskell2010 report. For example:

> foreign import ... foo :: IO CInt -> IO CInt

The type of @foo@ is 'Marshallable', but it is not a valid type for a foreign
import. 'IO' should (for the most part) only appear in a function result.

Moreover, instances of the 'Marshallable' class are not generated magically for
newtypes. This means that the class and its default instances provided in this
module are not /complete/ with respect to marshallable types as described in the
Haskell2010 report. For example:

> newtype MyCInt = MyCInt CInt
> foreign import ... bar :: IO MyCInt -> IO CInt

The type of @bar@ is not 'Marshallable', but it /is/ a valid type for a foreign
import, because the compiler can see that 'MyCInt' coerces to a 'CInt'.

=== Instances generated by hs-bindgen

@hs-bindgen@ generates 'Marshallable' instances for the newtypes that it
generates if the underlying type has a 'Marshallable' instance as well. It does
this using newtype-deriving:

> newtype S = S CInt
>   deriving newtype Marshallable
> newtype T a = T a
>   deriving newtype Marshallable
> newtype U = U (CChar -> IO CBool)
>   deriving newtype Marshallable

If a user wants to provide an instance for a (custom) newtype, then they should
be able to define one using newtype-deriving, provided the underlying type has a
'Marshallable' instance of course.
-}

{-------------------------------------------------------------------------------
  Class
-------------------------------------------------------------------------------}

-- | Haskell types that are marshallable through the FFI.
--
-- As a rule of thumb, if a type can appear in a foreign import, then it
-- /should/ have a 'Marshallable'.
class Marshallable a where
  type MarshallableBaseType a :: Type
  type MarshallableBaseType a = a
  toBaseType :: a -> MarshallableBaseType a
  fromBaseType :: MarshallableBaseType a -> a

toMarshallableBaseType :: Marshallable a => a -> MarshallableBaseType a
toMarshallableBaseType = toBaseType

fromMarshallableBaseType :: Marshallable a => MarshallableBaseType a -> a
fromMarshallableBaseType = fromBaseType

{-------------------------------------------------------------------------------
  Deriving-via
-------------------------------------------------------------------------------}

newtype ViaIdentity a = ViaIdentity a

instance Marshallable (ViaIdentity a) where
  type MarshallableBaseType (ViaIdentity a) = a

  {-# INLINE toBaseType #-}
  toBaseType (ViaIdentity x) = x

  {-# INLINE fromBaseType #-}
  fromBaseType x = ViaIdentity x

newtype ViaNewtype a = ViaNewtype a

instance Marshallable a => Marshallable (ViaNewtype a) where
  type MarshallableBaseType (ViaNewtype a) = MarshallableBaseType a

  {-# INLINE toBaseType #-}
  toBaseType (ViaNewtype x) = toBaseType x

  {-# INLINE fromBaseType #-}
  fromBaseType x = ViaNewtype (fromBaseType x)

{-------------------------------------------------------------------------------
  Instances: foreign types
-------------------------------------------------------------------------------}

instance (Marshallable a, Marshallable b) => Marshallable (a -> b) where
  type MarshallableBaseType (a -> b) = MarshallableBaseType a -> MarshallableBaseType b

  {-# INLINE toBaseType #-}
  toBaseType f = \x -> toBaseType (f (fromBaseType x))

  {-# INLINE fromBaseType #-}
  fromBaseType f = \x -> fromBaseType (f (toBaseType x))

{-------------------------------------------------------------------------------
  Instances: marshallable foreign result types
-------------------------------------------------------------------------------}

deriving via ViaIdentity () instance Marshallable ()

instance Marshallable a => Marshallable (IO a) where
  type MarshallableBaseType (IO a) = IO (MarshallableBaseType a)

  {-# INLINE toBaseType #-}
  toBaseType = fmap toBaseType

  {-# INLINE fromBaseType #-}
  fromBaseType = fmap fromBaseType

{-------------------------------------------------------------------------------
  Instances: marshallable foreign types
-------------------------------------------------------------------------------}

-- NOTE: we use 'ViaIdentity' rather than 'ViaNewtype' to derive 'Marshallable'
-- instances even for non-basic foreign types coming from the "Foreign.C"
-- modules. Most of these types, like 'CInt', are newtypes around basic foreign
-- types, but the specific basic foreign type depends on the platform\/operating
-- system. This is not a problem: the constructors for these non-basic types are
-- going to be in scope anyway. TODO: is this true?

-- === Prelude ===

-- Basic foreign types
deriving via ViaIdentity Char instance Marshallable Char
deriving via ViaIdentity Int instance Marshallable Int
deriving via ViaIdentity Double instance Marshallable Double
deriving via ViaIdentity Float instance Marshallable Float
deriving via ViaIdentity Bool instance Marshallable Bool

-- === Data.Int ===

-- Basic foreign types
deriving via ViaIdentity Int8 instance Marshallable Int8
deriving via ViaIdentity Int16 instance Marshallable Int16
deriving via ViaIdentity Int32 instance Marshallable Int32
deriving via ViaIdentity Int64 instance Marshallable Int64

-- === Data.Word ===

-- Basic foreign types
deriving via ViaIdentity Word instance Marshallable Word
deriving via ViaIdentity Word8 instance Marshallable Word8
deriving via ViaIdentity Word16 instance Marshallable Word16
deriving via ViaIdentity Word32 instance Marshallable Word32
deriving via ViaIdentity Word64 instance Marshallable Word64

-- === Foreign.Ptr ===

-- Basic foreign types
deriving via ViaIdentity (Ptr a) instance Marshallable (Ptr a)
deriving via ViaIdentity (FunPtr a) instance Marshallable (FunPtr a)

-- Newtypes around basic foreign types
deriving via ViaIdentity IntPtr instance Marshallable IntPtr
deriving via ViaIdentity WordPtr instance Marshallable WordPtr

-- === Foreign.StablePtr ===

-- Basic foreign types
deriving via ViaIdentity (StablePtr a) instance Marshallable (StablePtr a)

-- === Foreign.C.ConstPtr ===

-- Newtypes around basic foreign types
#if MIN_VERSION_base(4, 18, 0)
deriving via ViaIdentity (ConstPtr a) instance Marshallable (ConstPtr a)
#endif

-- === Foreign.C.Error ===

-- Newtypes around basic foreign types
deriving via ViaIdentity Errno instance Marshallable Errno

-- === Foreign.C.Types ===

-- Newtypes around basic foreign types
deriving via ViaIdentity CChar instance Marshallable CChar
deriving via ViaIdentity CSChar instance Marshallable CSChar
deriving via ViaIdentity CUChar instance Marshallable CUChar
deriving via ViaIdentity CShort instance Marshallable CShort
deriving via ViaIdentity CUShort instance Marshallable CUShort
deriving via ViaIdentity CInt instance Marshallable CInt
deriving via ViaIdentity CUInt instance Marshallable CUInt
deriving via ViaIdentity CLong instance Marshallable CLong
deriving via ViaIdentity CULong instance Marshallable CULong
deriving via ViaIdentity CPtrdiff instance Marshallable CPtrdiff
deriving via ViaIdentity CSize instance Marshallable CSize
deriving via ViaIdentity CWchar instance Marshallable CWchar
deriving via ViaIdentity CSigAtomic instance Marshallable CSigAtomic
deriving via ViaIdentity CLLong instance Marshallable CLLong
deriving via ViaIdentity CULLong instance Marshallable CULLong
deriving via ViaIdentity CBool instance Marshallable CBool
deriving via ViaIdentity CIntPtr instance Marshallable CIntPtr
deriving via ViaIdentity CUIntPtr instance Marshallable CUIntPtr
deriving via ViaIdentity CIntMax instance Marshallable CIntMax
deriving via ViaIdentity CUIntMax instance Marshallable CUIntMax

-- === Foreign.C.Types : Numeric types ===

-- Newtypes around basic foreign types
deriving via ViaIdentity CClock instance Marshallable CClock
deriving via ViaIdentity CTime instance Marshallable CTime
deriving via ViaIdentity CUSeconds instance Marshallable CUSeconds
deriving via ViaIdentity CSUSeconds instance Marshallable CSUSeconds

-- === Foreign.C.Types : Floating types ===

-- Newtypes around basic foreign types
deriving via ViaIdentity CFloat instance Marshallable CFloat
deriving via ViaIdentity CDouble instance Marshallable CDouble
