-- | Definitions used by bindings generated by @hs-bindgen@
module HsBindgen.Runtime.Prelude (
   -- * Types used by the C standard library external binding specification
    module HsBindgen.Runtime.LibC

    -- * Arrays
  , module HsBindgen.Runtime.SizedByteArray

    -- * Blocks
  , module HsBindgen.Runtime.Block

    -- * Constant pointers
  , module HsBindgen.Runtime.ConstPtr

    -- * Userland CAPI
  , module HsBindgen.Runtime.CAPI

    -- * Auxiliary
  , Data.List.unlines
  , HsBindgenRuntimePreludeIsInScope
  ) where

import Data.List qualified

import HsBindgen.Runtime.Block
import HsBindgen.Runtime.CAPI
import HsBindgen.Runtime.ConstPtr
import HsBindgen.Runtime.LibC
import HsBindgen.Runtime.SizedByteArray

-- | A type unique to "HsBindgen.Runtime.Prelude".
--
-- We use this type to ensure that "HsBindgen.Runtime.Prelude" is in scope when
-- generating bindings with Template Haskell at compile time. We print a helpful
-- error messaage if the module is not in scope.
data HsBindgenRuntimePreludeIsInScope
