/* automatically generated by rust-bindgen 0.71.1 */

pub type fun_ptr = ::std::option::Option<
    unsafe extern "C" fn(s: *mut forward_declaration),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct forward_declaration {
    pub f: fun_ptr,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of forward_declaration",
    ][::std::mem::size_of::<forward_declaration>() - 8usize];
    [
        "Alignment of forward_declaration",
    ][::std::mem::align_of::<forward_declaration>() - 8usize];
    [
        "Offset of field: forward_declaration::f",
    ][::std::mem::offset_of!(forward_declaration, f) - 0usize];
};
