-- | Shared utilities for fixture compilation
--
-- Fixtures are compiled directly via @ghc@ (or @haddock --ghc@).
--
-- The GHC environment file is generated by @cabal build@ (via
-- @write-ghc-environment-files: always@ in @cabal.project@) and lists all
-- package databases and visible packages from the main project build.
-- Individual fixtures are then compiled in parallel.
--
module Test.HsBindgen.Fixtures.Utils (
    -- * Name sanitization
    sanitizeLibName
    -- * Fixture environment setup
  , setupFixtureEnv
    -- * GHC options
  , sharedGhcOptions
    -- * Direct GHC compilation
  , runDirectGhcBuild
  ) where

import Control.Concurrent.Async (forConcurrently)
import Control.Concurrent.QSem (newQSem, signalQSem, waitQSem)
import Control.Exception (bracket_)
import Control.Monad (filterM)
import Data.List (isPrefixOf, stripPrefix)
import Data.Map.Strict (Map)
import Data.Map.Strict qualified as Map
import GHC.Conc (getNumProcessors)
import System.Directory (createDirectoryIfMissing, doesPathExist, listDirectory)
import System.Environment (getEnvironment)
import System.Exit (ExitCode (..))
import System.FilePath (isAbsolute, pathSeparator, takeDirectory, (<.>), (</>))
import System.IO (readFile')
import System.Process (CreateProcess (..), proc, readCreateProcessWithExitCode)

{-------------------------------------------------------------------------------
  Name sanitization
-------------------------------------------------------------------------------}

-- | Sanitize test name for use as a library name
--
-- Sanitization logic:
--
-- * @.DIGIT@ -> @vDIGIT@  (avoids version-like segments)
-- * @_DIGIT@ -> @nDIGIT@  (avoids version-like segments)
-- * Remaining @/@, @_@, @.@ -> @-@
--
sanitizeLibName :: String -> String
sanitizeLibName = go
  where
    go [] = []
    go ('.':c:rest)
      | c `elem` ['0'..'9'] = 'v' : c : go rest
    go ('_':c:rest)
      | c `elem` ['0'..'9'] = 'n' : c : go rest
    go ('/':rest) = '-' : go rest
    go ('_':rest) = '-' : go rest
    go ('.':rest) = '-' : go rest
    go (c:rest) = c : go rest

{-------------------------------------------------------------------------------
  Fixture environment setup
-------------------------------------------------------------------------------}

-- | Obtain the GHC environment for fixture compilation
--
-- Finds the @.ghc.environment.*@ file generated by @cabal build@ in the repo
-- root.  This file is created because @cabal.project@ contains
-- @write-ghc-environment-files: always@.  It lists all package databases and
-- visible packages from the main project build, so no extra @cabal build@ or
-- @cabal exec@ is needed.
--
-- Returns include directories and path to the GHC environment file.
setupFixtureEnv ::
     FilePath  -- ^ Repo root
  -> IO ([FilePath], FilePath)
     -- ^ (include directories, GHC environment file)
setupFixtureEnv repoRoot = do
    let hsBindgenDir = repoRoot </> "hs-bindgen"
        includeDirs  =
          [ hsBindgenDir </> "examples"
          , hsBindgenDir </> "examples" </> "golden"
          , hsBindgenDir </> "musl-include" </> "x86_64"
          ]

    envFile <- discoverGhcEnvFile repoRoot
    return (includeDirs, envFile)

{-------------------------------------------------------------------------------
  GHC options
-------------------------------------------------------------------------------}

-- | GHC warning and C compiler options shared across all fixture compilations
sharedGhcOptions :: [String]
sharedGhcOptions =
    [ "-Wall"
    , "-Wincomplete-uni-patterns"
    , "-Wincomplete-record-updates"
    , "-Wmissing-exported-signatures"
    , "-Widentities"
    , "-Wredundant-constraints"
    , "-Wpartial-fields"
    , "-Wcpp-undef"
    , "-Wno-unused-matches"
    , "-optc-std=gnu2x"
    , "-optc-Wno-deprecated-declarations"
    , "-optc-Wno-attributes"
    ]

{-------------------------------------------------------------------------------
  Direct GHC / haddock compilation
-------------------------------------------------------------------------------}

-- | Compile fixture modules directly via @ghc@ or @haddock@, bypassing
-- cabal's internal library machinery
--
-- Each invocation returns its own exit code and stderr, so per-fixture error
-- attribution is trivial (no stderr parsing needed).
--
-- When @haddockDir@ is 'Nothing', uses @ghc --make -no-link@ (compile only).
-- When @haddockDir@ is @'Just' dir@, uses @haddock --ghc --html@ to compile
-- and generate browsable Haddock documentation.
runDirectGhcBuild ::
     FilePath
     -- ^ Working directory (temp dir for output isolation)
  -> FilePath
     -- ^ GHC environment file (from 'setupFixtureEnv')
  -> [String]
     -- ^ GHC options (warnings, @-optc@ flags, extensions)
  -> [String]
     -- ^ Include directories (for @-I@ flags)
  -> Maybe FilePath
     -- ^ Haddock output directory, or 'Nothing' for compile-only
  -> [(String, FilePath, [String], [String])]
     -- ^ (library name, source directory, module names, extra GHC args)
  -> IO (Map String (Either String ()))
runDirectGhcBuild workDir envFile ghcOpts includeDirs mHaddockDir jobs = do
    -- Set up environment with GHC_ENVIRONMENT pointing to the env file
    baseEnv <- getEnvironment
    let compileEnv = ("GHC_ENVIRONMENT", envFile)
                   -- We have to filter the GHC_ENVIRONMENT file that the test
                   -- suite generates, which doesn't have all the packages TH
                   -- and PP compilation needs.
                   : filter ((/= "GHC_ENVIRONMENT") . fst) baseEnv

    -- Compile each fixture in parallel, bounded by available cores
    caps <- max 1 <$> getNumProcessors
    sem <- newQSem caps
    results <- forConcurrently jobs $
      \(libName, srcDir, moduleNames, extraArgs) ->
        bracket_ (waitQSem sem) (signalQSem sem) $ do
          let outDir = workDir </> "out" </> libName
          createDirectoryIfMissing True outDir
          let allGhcOpts = ["-XHaskell2010"]
                        ++ ghcOpts
                        ++ extraArgs
                        ++ ["-I" ++ dir | dir <- includeDirs]
                        ++ ["-i" ++ srcDir]
                        ++ ["-odir", outDir, "-hidir", outDir]
                        ++ ["-stubdir", outDir]
              args = case mHaddockDir of
                Nothing ->
                  -- ghc --make: pass module names
                  ["--make", "-no-link"] ++ allGhcOpts ++ moduleNames
                Just haddockDir ->
                  -- haddock --ghc: pass source file paths
                  let haddockOutDir = haddockDir </> libName
                      sources = map (moduleToSrc srcDir) moduleNames
                  in  ["--ghc", "--html", "-o", haddockOutDir]
                   ++ map ("--optghc=" ++) allGhcOpts
                   ++ sources
              cmd = case mHaddockDir of
                Nothing -> "ghc"
                Just _  -> "haddock"
              compileProc = (proc cmd args)
                            { cwd = Just workDir
                            , env = Just compileEnv
                            }
          (exitCode, _stdout, stderr) <-
            readCreateProcessWithExitCode compileProc ""
          let result = case exitCode of
                ExitSuccess -> Right ()
                _           -> Left stderr
          return (libName, result)

    return $ Map.fromList results

-- | Convert a module name to a source file path
--
-- @Example.Safe@ -> @\<srcDir\>\/Example\/Safe.hs@
moduleToSrc :: FilePath -> String -> FilePath
moduleToSrc srcDir modName = srcDir </> map dotToSep modName <.> "hs"
  where
    dotToSep '.' = pathSeparator
    dotToSep c   = c

-- | Find the @.ghc.environment.*@ file in the given directory
--
-- Generated by cabal when @write-ghc-environment-files: always@ is set in
-- @cabal.project@.  Env files reference package DBs under the shared cabal
-- store; if the store has been cleaned since the file was written, the
-- referenced paths no longer exist and @ghc@ will fail with cryptic linker
-- errors.  We detect that case here and direct the user to rerun the build.
discoverGhcEnvFile :: FilePath -> IO FilePath
discoverGhcEnvFile dir = do
    entries <- listDirectory dir
    envFile <- case filter (".ghc.environment." `isPrefixOf`) entries of
      [f] -> return (dir </> f)
      []  -> fail $ "No .ghc.environment file found in " ++ dir
                 ++ ". Ensure cabal.project has: write-ghc-environment-files: always"
      fs  -> fail $ "Multiple .ghc.environment files in " ++ dir
                 ++ ": " ++ show fs
    checkPackageDbsExist envFile
    return envFile

-- | Verify that every @package-db@ path referenced by an env file exists
--
-- Fails with a clear message when any path is missing (typically because the
-- cabal store was cleaned after the env file was written).
checkPackageDbsExist :: FilePath -> IO ()
checkPackageDbsExist envFile = do
    contents <- readFile' envFile
    -- Paths in an env file are resolved relative to the env file's directory
    -- (the project root), not the process CWD.
    let envDir = takeDirectory envFile
        resolve p = if isAbsolute p then p else envDir </> p
        dbPaths = [ resolve p | line <- lines contents
                              , Just p <- [stripPrefix "package-db " line]
                              ]
    missing <- filterM (fmap not . doesPathExist) dbPaths
    case missing of
      [] -> return ()
      _  -> fail $ unlines $
        [ "Stale GHC environment file: " ++ envFile
        , "The following package-db paths no longer exist:"
        ] ++ map ("  " ++) missing ++
        [ ""
        , "This usually means the cabal store was cleaned after the env"
        , "file was written.  Rerun `cabal build all` to regenerate it."
        ]
