name: c-yaml example
description: Build and run the c-yaml example

runs:
  using: composite
  steps:
    - name: Run generation and build script
      shell: bash
      working-directory: ./examples/c-yaml
      run: ./generate-and-run.sh
