name: HLint

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  hlint:
    name: HLint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: 'Set up HLint'
      uses: haskell-actions/hlint-setup@v2
      with:
        version: '3.10'

    - name: 'Run HLint'
      uses: haskell-actions/hlint-run@v2
      with:
        path: '[ "hs-bindgen/src/", "hs-bindgen/app/", "hs-bindgen/src-internal/"  ]'
        fail-on: suggestion
