name: Check links

on:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

env:
  # Run nightly on the default branch to catch links that break unexpectedly, for
  # example because they link to web pages that do not exist anymore.
  nightly: ${{ github.event_name == 'schedule' }}

jobs:
  # Checks links in Markdown, HTML and text files using lychee.
  #
  # We are mostly interested in checking links in our manual, which consists of
  # Markdown files.
  #
  # <https://github.com/marketplace/actions/lychee-broken-link-checker>
  check-links:
    name: Check links with lychee
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      # NOTE: if lychee-action runs too slowly in the future, then we can use
      # caching to improve performance. A tutorial for configuring the cache can
      # be found in the lychee-action README:
      #
      # <https://github.com/lycheeverse/lychee-action/blob/master/README.md>
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        env:
          # Default arguments taken directly from:
          # <github.com/lycheeverse/lychee-action/blob/master/action.yml>
          default-args: "--verbose --no-progress './**/*.md' './**/*.html' './**/*.rst'"
          # With --include-fragments we also enable anchor link checking.
          #
          # Unfortunately, broken reference links are not checked because it is
          # not (yet) implemented:
          # <https://github.com/lycheeverse/lychee/issues/456>
          custom-args: "--include-fragments"

        with:
          args: "${{ env.default-args }} ${{ env.custom-args }}"
          fail: true
          failIfEmpty: true

      # Post a comment on an issue to notify developers of failures
      #
      # This step is based on:
      # <https://docs.github.com/en/actions/tutorials/manage-your-work/add-comments-with-labels>
      - name: Notifications for failure (Nightly)
        # NOTE: env.nightly is a stringized boolean, so we perform string
        # equality rather than boolean equality
        if: ${{ failure() && env.nightly == 'true' }}
        id: notifications
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: 1972
          BODY: >
            Nightly CI for the Link Checker workflow failed.
            See the results at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.
