name: Cabal check

on:
  push:
    branches:
    - "main"
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-cabal:
    name: Cabal check
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v7

    - name: 🛠️ Setup Haskell
      id: setup-haskell
      uses:  haskell-actions/setup@v2
      with:
        ghc-version: "9.6"
        cabal-version: "3.16"
        cabal-update: false

    - name: 🎗️ Lint with cabal
      run: ./scripts/ci/run-cabal-check.sh
