name: Merge queue
on:
  pull_request:
    branches:
      - main
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    # PRs can only be added to the MQ when all "required" checks pass.
    # PRs can only be merged into `main` when all "required" checks pass in the MQ.
    #
    # So we need to always run all checks, but skip PR view jobs in the MQ, and
    # MQ jobs in the PR view.
    if: ${{ github.event_name == 'merge_group' }}
    strategy:
      matrix:
        include:
          - runner: 'macos-latest'
            ghc:    '9.4.8'
            llvm:   '14'
          - runner: 'windows-latest'
            ghc:    '9.4.8'
            llvm:   '14'
          # # We test the following combination of parameters in Haskell-CI.
          # - runner: 'ubuntu-latest'
          #   ghc:    '9.4.8'
          #   llvm:   '14'
          - runner: 'ubuntu-latest'
            ghc:    '9.4.8'
            llvm:   '16'
          - runner: 'ubuntu-latest'
            ghc:    '9.4.8'
            llvm:   '18'
          - runner: 'ubuntu-latest'
            ghc:    '9.4.8'
            llvm:   '20'
      fail-fast: false
    uses: ./.github/workflows/haskell-simple-base.yml
    with:
      runner: ${{ matrix.runner }}
      ghc:    ${{ matrix.ghc }}
      llvm:   ${{ matrix.llvm }}
