name: Pull request
on:
  pull_request:
    branches:
      - main
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    # PRs can only be added to the MQ when all "required" checks pass.
    # PRs can only be merged into `main` when all "required" checks pass in the MQ.
    #
    # So we need to always run all checks, but skip PR view jobs in the MQ, and
    # MQ jobs in the PR view.
    if: ${{ github.event_name == 'pull_request' }}
    strategy:
      matrix:
        runner: ['ubuntu-latest']
        ghc:    ['9.4.8']
        llvm:   ['15']
    uses: ./.github/workflows/haskell-simple-base.yml
    with:
      runner: ${{ matrix.runner }}
      ghc:    ${{ matrix.ghc }}
      llvm:   ${{ matrix.llvm }}
