name: Haskell-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Nix - Linux - Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v16
      with:
        name: hs-bindgen
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix develop --print-build-logs --command bash -c "cabal update; cabal build all; cabal test all"
