name: Manual (macOS)
description: Build and run the manual on macOS

# If needed, we can SSH into the machine executing the job and
# figure out what's going on:
# - name: Setup tmate session
#   uses: mxschmitt/action-tmate@v3

runs:
  using: composite
  steps:
    # The MacOS assembler has an issue with Unicode characters so we don't set
    # SUPPORTS_UNICODE.

    # We do not pass '-DSUPPORTS_UNICODE'.
    #
    # In `manual_examples.{c,h}` and `manual/hs/app/RunManual.hs` we have CPP
    # clauses to replace the 拜拜 and ϒ functions by ByeBye and Gamma. The
    # former, because LLVM itermediate representation (IR) does not support
    # Unicode characters and the latter because Apple's assembler also does not
    # support Unicode characters.
    - name: Create cabal.project in ./manual/hs
      shell: bash
      working-directory: ./manual/hs
      run: cp cabal.project.ci cabal.project

    - name: Generate bindings, build and run the manual
      shell: bash
      working-directory: ./manual
      run: ./generate-and-run.sh
